---
# Defaults overridden by group_vars/all.yml or playbook vars.

xray_runtime_user: xray
xray_runtime_group: xray
xray_install_dir: "{{ xray_install_root | default('/opt/xray') }}"
xray_etc_dir: "{{ xray_config_dir | default('/etc/xray') }}"
xray_log_path: "{{ xray_log_dir | default('/var/log/xray') }}"
