#!/usr/bin/env bash
# Safe `make destroy`. Asks for explicit confirmation twice, removes the
# `prevent_destroy` lifecycle block in a temp override file (so the source
# stays clean), runs `terraform destroy`, removes the override, and clears
# the inventory.
#
# Required env: PROVIDER, ENV.
set -euo pipefail

PROVIDER="${PROVIDER:-upcloud}"
ENV="${ENV:-prod}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/providers/${PROVIDER}"
INV="${REPO_ROOT}/ansible/inventory/generated.ini"
OVERRIDE="${TF_DIR}/_destroy_override.tf"
TFVARS="${TF_DIR}/environments/${ENV}.tfvars"

if [[ ! -d "$TF_DIR" ]]; then
  echo "no terraform root: $TF_DIR" >&2
  exit 1
fi

if [[ ! -f "$TFVARS" ]]; then
  echo "no tfvars: $TFVARS" >&2
  exit 1
fi

trap 'rm -f "$OVERRIDE"' EXIT

cat <<EOF

DANGER: this will destroy the VPS and firewall managed by:
  ${TF_DIR}
  ENV=${ENV}

Existing clients on this node will lose connectivity. The Terraform state
file will record the destruction; back it up first if you want to keep an
audit trail.

EOF

read -r -p "Type the server hostname to confirm (Ctrl-C to abort): " typed
expected="$(grep -E '^server_name' "$TFVARS" | head -1 | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/')"
if [[ "$typed" != "$expected" ]]; then
  echo "hostname mismatch (expected: $expected) — aborting" >&2
  exit 1
fi

read -r -p "Type DESTROY to proceed: " word
if [[ "$word" != "DESTROY" ]]; then
  echo "aborted"
  exit 1
fi

# Drop a temporary override that disables prevent_destroy. Terraform merges
# *_override.tf into the working configuration; this lets us destroy without
# editing the canonical main.tf (which would dirty the working tree).
cat > "$OVERRIDE" <<EOF
# Generated by scripts/destroy.sh — removed automatically when destroy completes.
# Disables prevent_destroy on the VPS so terraform destroy can proceed.
resource "upcloud_server" "vpn" {
  lifecycle {
    prevent_destroy = false
  }
}
EOF

# Plan destroy first so the operator sees the diff
terraform -chdir="$TF_DIR" plan -destroy \
  -var-file="environments/${ENV}.tfvars" \
  -out="${ENV}.destroy.tfplan"

read -r -p "Apply this destroy plan? [yes/NO]: " final
if [[ "$final" != "yes" ]]; then
  echo "aborted"
  exit 1
fi

terraform -chdir="$TF_DIR" apply "${ENV}.destroy.tfplan"
rm -f "${TF_DIR}/${ENV}.destroy.tfplan"

# Clean inventory and ask if they want a state backup
if [[ -f "$INV" ]]; then
  rm -f "$INV"
  echo "removed $INV"
fi

cat <<'EOF'

Destroyed. The Terraform state still records the destruction; on the next
plan it will be empty. Ensure you've kept an encrypted backup of the
pre-destroy state if you might want to forensically inspect what existed:

    PROVIDER=… ENV=… ./scripts/backup-tf-state.sh

(The backup script reads the current state file. After destroy, the state
shows nothing useful; back up *before* destroy if you need a record.)
EOF
