#!/usr/bin/env bash
# Provision a hardware-backed age identity on a YubiKey (PIV applet).
# Closes the "operator workstation lost" failure mode: the SOPS blob
# stays useless to anyone without physical access to the YubiKey, even
# if they have the encrypted file.
#
# What this script does:
#   1. Verify age and age-plugin-yubikey are installed.
#   2. Generate a fresh age identity on the YubiKey's PIV slot.
#      The corresponding age recipient (age1yubikey1…) is printed.
#   3. Optionally re-encrypt every existing SOPS file under
#      ~/.config/vpn-provision/ to include the new recipient.
#
# What this script does NOT do:
#   * remove the software age recipient from existing files; that's
#     a deliberate post-migration step (see SECRETS.md). Removing it
#     before you've verified hardware-backed decrypts on every host
#     is how operators lose access permanently.
#   * choose a PIN policy for you; age-plugin-yubikey will prompt.
#
# Usage:
#   scripts/setup-yubikey-age.sh                   # generate + print
#   scripts/setup-yubikey-age.sh --reencrypt        # also `sops updatekeys`
set -euo pipefail

CONFIG_DIR="${HOME}/.config/vpn-provision"
mkdir -p "$CONFIG_DIR"; chmod 0700 "$CONFIG_DIR"

REENCRYPT=0
[[ "${1:-}" == "--reencrypt" ]] && REENCRYPT=1

for tool in age age-plugin-yubikey sops; do
  command -v "$tool" >/dev/null 2>&1 || {
    cat >&2 <<EOF
missing tool: $tool

Install on macOS:
  brew install age age-plugin-yubikey sops

Install on Debian/Ubuntu:
  sudo apt install age
  # age-plugin-yubikey: see https://github.com/str4d/age-plugin-yubikey
  # sops: https://github.com/getsops/sops/releases
EOF
    exit 2
  }
done

echo "==> Probing YubiKey PIV applet"
age-plugin-yubikey --list-all

cat <<'EOF'

==> Generating a hardware-backed age identity

You'll be prompted for:
  * Slot to use (default: 1, the PIV authentication slot)
  * PIN / touch policy
  * Optionally: a friendly name for the identity

After completion, the script prints the public recipient. Append it
to any of these places:

  * .sops.yaml in this repo's secrets dir (recommended)
  * Re-encrypt existing SOPS files via `sops updatekeys` (this
    script will offer to do it for you when --reencrypt is set)

Keep the printed recipient — it never changes for this YubiKey slot,
so document it (1Password / hardware token register / equivalent).

EOF
read -r -p "Continue? [yes/NO]: " ans
[[ "$ans" == "yes" ]] || { echo "aborted"; exit 1; }

# Run the generator. age-plugin-yubikey writes its identity to stderr
# and prints the recipient as one of the lines containing "age1yubikey".
age-plugin-yubikey --generate

echo
echo "==> Verifying the new identity is discoverable"
age-plugin-yubikey --identity > "${CONFIG_DIR}/yubikey-identity.txt"
chmod 0600 "${CONFIG_DIR}/yubikey-identity.txt"
RECIPIENT="$(grep -m1 '^age1yubikey' "${CONFIG_DIR}/yubikey-identity.txt" || true)"
if [[ -z "$RECIPIENT" ]]; then
  echo "could not extract the age1yubikey… recipient" >&2
  exit 1
fi
echo "  recipient: ${RECIPIENT}"
echo "  identity stub saved at: ${CONFIG_DIR}/yubikey-identity.txt"

if (( REENCRYPT )); then
  echo
  echo "==> Re-encrypting existing SOPS files to include the YubiKey recipient"

  if [[ ! -f "${CONFIG_DIR}/.sops.yaml" ]]; then
    cat > "${CONFIG_DIR}/.sops.yaml" <<EOFY
# Generated by scripts/setup-yubikey-age.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
creation_rules:
  - path_regex: '\\.sops\\.yaml$'
    age: >-
      ${RECIPIENT}
EOFY
    echo "  wrote ${CONFIG_DIR}/.sops.yaml — add software-age recipient manually if you keep dual-key access"
  else
    echo "  ${CONFIG_DIR}/.sops.yaml exists — adding YubiKey recipient idempotently"
    grep -q "$RECIPIENT" "${CONFIG_DIR}/.sops.yaml" || \
      echo "  TODO: manually add '${RECIPIENT}' to creation_rules in ${CONFIG_DIR}/.sops.yaml"
  fi

  shopt -s nullglob
  for f in "${CONFIG_DIR}"/*.secrets.sops.yaml; do
    echo "  sops updatekeys ${f}"
    sops updatekeys -y "$f" || echo "  (warn) updatekeys failed for $f — re-run manually"
  done
  shopt -u nullglob
fi

cat <<EOF

==> Done.

Next:
  * verify decryption: SOPS_AGE_KEY_FILE=${CONFIG_DIR}/yubikey-identity.txt \\
      sops --decrypt ${CONFIG_DIR}/prod.secrets.sops.yaml | head
  * once decryption is confirmed on every operator workstation, remove
    the software-age recipient via 'sops updatekeys' on each blob.
    DO NOT do this before verifying — the YubiKey is now the sole
    decryption path.
EOF
